[build]
  command = "ng build --configuration production && ng run {projectName}:serverless:production"
  functions = "./functions"
  publish = "dist/portfolio/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-angular-universal"
