[build]
  command = "npm run build:ssr"
  publish = "dist/portfolio/browser"
  functions = "dist/portfolio/functions"

[[plugins]]
  package = "netlify-plugin-prerender-spa"

  [plugins.inputs]
    distDir = "dist/portfolio/browser"
    routes = "/*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
