[build]
  command = "ng build --configuration production && ng run portfolio:serverless:production"
  functions = "./functions"
  publish = "dist/portfolio/browser"

[[plugins]]
  package = "@netlify/plugin-angular-universal"
  [plugins.inputs]
    browserTarget = "portfolio:build:browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
