[build]
  command = "ng build --configuration production && ng run portfolio:serverless:production"
  publish = "dist/portfolio/browser"
  functions = "dist/portfolio/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
